---
clone:
  tags: true
  path: github.com/casualjim/go-app

build:
  compile:
    image: golang:1.7
    pull: true
    commands:
      - go get -u github.com/axw/gocov/gocov
      - go get -u gopkg.in/matm/v1/gocov-html
      - go get -u github.com/cee-dub/go-junit-report
      - go get -t ./...
      - ./build.sh

publish:
  coverage:
    server: https://coverage.vmware.run
    token: $$GITHUB_TOKEN
    threshold: 70
    must_increase: true